# Generated by Django 5.1.2 on 2025-11-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorias',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de la mentoría'),
        ),
    ]
