# Generated by Django 5.1.2 on 2025-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0002_alter_mentorias_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorias',
            name='hora',
            field=models.TimeField(default='10:00', verbose_name='Hora de la mentoría'),
            preserve_default=False,
        ),
    ]
