# Generated by Django 5.1.2 on 2025-12-02 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_remove_horarios_bloque_horarios_hora_fin_and_more'),
        ('mentorias', '0003_mentorias_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorias',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='mentorias',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mentorias',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorias',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorias',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.horarios'),
        ),
        migrations.AddField(
            model_name='mentorias',
            name='usuario_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorias',
            name='usuario_especialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorias',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
