# Generated by Django 5.1.2 on 2025-11-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='recurso',
            new_name='recursos',
        ),
    ]
