# Generated by Django 5.1.2 on 2025-11-17 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(choices=[('Psicología Clínica', 'Psicología Clínica'), ('Psicología Organizacional', 'Psicología Organizacional'), ('Neuropsicología', 'Neuropsicología'), ('Psicopedagogía', 'Psicopedagogía')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especialista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
