# Generated by Django 5.1.2 on 2025-11-17 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='especialista',
            name='correo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especialista', to=settings.AUTH_USER_MODEL),
        ),
    ]
