# Generated by Django 5.1.2 on 2025-11-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0002_remove_especialista_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='correo',
            new_name='usuario',
        ),
    ]
