# Generated by Django 5.1.2 on 2025-11-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0003_rename_correo_especialista_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='telefono',
        ),
    ]
