# Generated by Django 5.1.2 on 2025-11-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0004_remove_especialista_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='nombre_completo',
        ),
    ]
