# Generated by Django 5.1.2 on 2025-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
