# Generated by Django 5.1.2 on 2025-11-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('clinica', 'Psicología Clínica'), ('organizacional', 'Psicología Organizacional'), ('neuro', 'Neuropsicología'), ('psicopedagogia', 'Psicopedagogía')], max_length=50, null=True),
        ),
    ]
