# Generated by Django 5.1.2 on 2025-11-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='especialidad',
        ),
    ]
