# Generated by Django 5.1.2 on 2025-11-12 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursos',
            old_name='nombre',
            new_name='nombre_recurso',
        ),
        migrations.AddField(
            model_name='recursos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recursos',
            name='tipo',
            field=models.CharField(choices=[('charla', 'Charla'), ('taller', 'Taller'), ('articulo', 'Artículo')], max_length=50),
        ),
    ]
