# Generated by Django 5.1.2 on 2025-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_rename_nombre_recursos_nombre_recurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='imagen_recurso',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
