# Generated by Django 5.1.2 on 2025-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_recursos_imagen_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
