# Generated by Django 5.1.2 on 2025-12-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_alter_recursos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='imagen_recurso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
