# Generated by Django 5.1.2 on 2025-12-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_alter_recursos_imagen_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
