# Generated by Django 5.1.2 on 2025-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='horarios',
            name='bloque',
            field=models.CharField(choices=[('09:00-10:00', '09:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('14:00-15:00', '02:00 PM - 03:00 PM'), ('15:00-16:00', '03:00 PM - 04:00 PM')], default='09:00-10:00', max_length=20, verbose_name='Bloque horario'),
            preserve_default=False,
        ),
    ]
