# Generated by Django 5.1.2 on 2025-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_remove_horarios_hora_fin_remove_horarios_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='bloque',
        ),
        migrations.AddField(
            model_name='horarios',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
    ]
